### ISSUE TITLE
Workshop search box broken / Characters type numbers and symbols

### ISSUE THREAD

**Issue by UltraBlackLinux** [2048khz-gachi-rmx/WSMount#1]
Hey there,
I noticed that typing in the search box in the Steam workshop results in numbers being typed instead of characters. Furthermore some keys seem to type * - / and even other characters, even though they shouldn't.
Please fix this!
Thanks!

**Comment by 2048khz-gachi-rmx** [comment]
What game branch are you on and what OS are you using? IIRC Chromium/x64 branches have issues with keyboard input on Linux (and macOS I think?) See: https://github.com/Facepunch/garrysmod-issues/issues/4464

**Comment by UltraBlackLinux** [comment]
Welp yeah. Linux on the chromium branch. I wanted to try out this addon since the steam overlay is apparently broken or disabled on chromium...
And oh yeah, apparently keyboard input is also broken in the workshop search bar, I never noticed that. Thank you for clearing that up!
